@StudentRecords_Api_HostAddress = https://localhost:7083


### Get all students

GET {{StudentRecords_Api_HostAddress}}/students
Accept: application/json


###


### Get student by ID

GET {{StudentRecords_Api_HostAddress}}/students/1
Accept: application/json


###


### Add a new student

POST {{StudentRecords_Api_HostAddress}}/students
Content-Type: application/json

{
  "id": 5,
  "name": "Gabby",
  "surname": "Smith",
  "age": 21,
  "course": "Cyber Security",
  "mark": 82
}


###


### Update student

PUT {{StudentRecords_Api_HostAddress}}/students/5
Content-Type: application/json

{
  "id": 5,
  "name": "Gabby",
  "surname": "Jones",
  "age": 22,
  "course": "Computer Science",
  "mark": 88
}


###


### Delete student

DELETE {{StudentRecords_Api_HostAddress}}/students/5


###